// import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthContext";

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['100', '200', '300', '400', '600', '700', '900'], // you can add more weights
//   display: 'swap',
//   variable: '--font-poppins',
// });

export const metadata = {
  title: "HappyInvoice - Online Invoice Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <AuthProvider>
        <body
          className={`antialiased`}>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
